//go:build all_tests || all_unit_tests || all_integration_tests || unit_tests || integration_tests

package rpm_test

import (
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

const (
	StreamMirror                     = "https://mirrors.edge.kernel.org/centos/8-stream/"
	BaseOSRepoWrongURL               = "https://mirrors.edge.kernel.org/centos/8-stream/BaseOS/x86_64/os/repodata/"
	BaseOSRepo                       = "https://mirrors.edge.kernel.org/centos/8-stream/BaseOS/x86_64/os/repodata/repomd.xml"
	VimCommonPackageCountInPrimaryDB = 16
)

var (
	AppStreamDBs = []string{
		"https://mirrors.edge.kernel.org/centos/8-stream/AppStream/x86_64/os/repodata/61f6a65a0fb3f5cf50072b2d0ccc0a5dbd48b72e627166a552162b224a6a9c4e-filelists.xml.gz",
		"https://mirrors.edge.kernel.org/centos/8-stream/AppStream/x86_64/os/repodata/6a43fcc51790f0d0c43c6ed91ca8353dbba4d95a3feb027df20f64d2d1408bf4-primary.xml.gz",
		"https://mirrors.edge.kernel.org/centos/8-stream/AppStream/x86_64/os/repodata/c2781f59ba46545704235f2a703d3ee9e531e6d112c9b4f1ab66b8e7bc4d8957-other.xml.gz",
	}
	StreamRepos = []string{
		"https://mirrors.edge.kernel.org/centos/8-stream/RT/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/PowerTools/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/PowerTools/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/HighAvailability/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/Devel/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/x86_64/tdx-devel/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/NFV/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/opstools/x86_64/collectd-5/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/BaseOS/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/PowerTools/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/ResilientStorage/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/opstools/ppc64le/collectd-5/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/aarch64/advancedvirt-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/AppStream/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/Devel/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/x86_64/openstack-ussuri/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/x86_64/openstack-xena/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/ResilientStorage/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/core/x86_64/centos-plus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/x86_64/packages-main/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/centosplus/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/x86_64/advancedvirt-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/x86_64/ovirt-45/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/gluster-8/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/ppc64le/openstack-train/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/aarch64/ovirt-44/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/ppc64le/openstack-ussuri/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/ppc64le/tdx-devel/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/samba-415/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/aarch64/openstack-victoria/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/ppc64le/openstack-victoria/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/x86_64/openstack-victoria/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/opstools/aarch64/collectd-5/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/ppc64le/openstack-yoga/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/HighAvailability/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/x86_64/ovirt-44/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/ppc64le/ovirt-45/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/aarch64/tdx-devel/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/aarch64/packages-rebuild/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/aarch64/packages-facebook/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/x86_64/packages-spin/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/aarch64/packages-main/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/messaging/ppc64le/qpid-proton/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/ppc64le/openstack-xena/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/ppc64le/kata-containers/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-413/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/ceph-quincy/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/nfsganesha-3/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/ceph-octopus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/x86_64/packages-intel/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/HighAvailability/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-416/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-414/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/samba-413/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/extras/aarch64/extras-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/ceph-nautilus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/ppc64le/packages-userspace/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/ppc64le/ovirt-44/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-417/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/x86_64/packages-rebuild/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/samba-418/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/nfsganesha-4/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/ceph-reef/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/centosplus/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/gluster-9/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/x86_64/packages-main/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/x86_64/kata-containers/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/gluster-10/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/aarch64/kata-containers/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/AppStream/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/x86_64/openstack-yoga/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/centosplus/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/ceph-reef/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/aarch64/ovirt-45/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/x86_64/packages-experimental/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/aarch64/openstack-ussuri/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/aarch64/openstack-yoga/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/Devel/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/extras/x86_64/extras-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/messaging/aarch64/qpid-proton/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-418/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/x86_64/packages-facebook/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-415/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/ceph-quincy/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/ceph-octopus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/gluster-11/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/nfsganesha-4/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/gluster-9/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/ceph-nautilus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/gluster-11/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/nfv/aarch64/network-extras/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/ceph-pacific/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/ppc64le/packages-hotfixes/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/aarch64/openstack-train/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/samba-418/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/gluster-11/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/gluster-8/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/samba-417/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/virt/ppc64le/advancedvirt-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/nfv/x86_64/network-extras/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/nfv/x86_64/openvswitch-2/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/samba-416/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/ppc64le/packages-spin/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/extras/ppc64le/extras-common/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/samba-413/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/messaging/ppc64le/rabbitmq-38/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/messaging/aarch64/rabbitmq-38/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/ceph-octopus/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/x86_64/packages-userspace/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/aarch64/packages-userspace/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/samba-414/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/messaging/x86_64/rabbitmq-38/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/kmods/ppc64le/packages-rebuild/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/nfv/ppc64le/openvswitch-2/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/ppc64le/samba-419/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cr/aarch64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/x86_64/samba-414/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/ceph-reef/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cloud/aarch64/openstack-wallaby/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/storage/aarch64/samba-419/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/extras/ppc64le/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/extras/x86_64/os/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/hyperscale/aarch64/packages-hotfixes/repodata/repomd.xml",
		"https://mirrors.edge.kernel.org/centos/8-stream/cr/ppc64le/os/repodata/repomd.xml",
	}
)

func TestRpm(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Rpm Suite")
}
